out_dir: results
metric_best: accuracy
wandb:
  use: True
  project: arxiv
dataset:
  format: OGB
  name: ogbn-arxiv
  task: node
  task_type: classification
  transductive: True
  node_encoder: False
  node_encoder_name: LinearNode+RWSE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: DummyEdge
  edge_encoder_bn: False
posenc_RWSE:
  enable: False
  kernel:
    times_func: range(1,17)
  model: Linear
  dim_pe: 16
  raw_norm_type: BatchNorm
train:
  mode: custom
  batch_size: 1
  eval_period: 1
  ckpt_period: 100
model:
  type: gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: add
gnn:
  head: default
  layers_pre_mp: 1
  layers_mp: 8
  layers_post_mp: 1
  dim_inner: 239
  layer_type: gcnconv
  batchnorm: True
  residual: True
  act: relu
  dropout: 0.3
  agg: sum
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 600
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 10
  min_lr: 1e-5