out_dir: results
metric_best: accuracy
wandb:
  use: True
  project: malnet
dataset:
  format: PyG-MalNetTiny
  name: LocalDegreeProfile
  task: graph
  task_type: classification
  transductive: False
  node_encoder: True
  node_encoder_name: LinearNode
  edge_encoder: True
  edge_encoder_name: DummyEdge
  edge_encoder_bn: False
posenc_ERN:
  enable: False
  model: Linear
  dim_pe: 8
  layers: 2
train:
  mode: custom
  batch_size: 16  
  eval_period: 1
  ckpt_period: 100
model:
  type: custom_gnn
  loss_fun: cross_entropy
  edge_decoding: dot
  graph_pooling: max
gnn:
  head: default
  layers_pre_mp: 1
  layers_mp: 8
  layers_post_mp: 3
  dim_inner: 122
  layer_type: gineconv
  batchnorm: True
  residual: True
  act: relu
  dropout: 0.0
  agg: sum
  normalize_adj: False
optim:
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.001
  max_epoch: 500
  scheduler: reduce_on_plateau
  reduce_factor: 0.5
  schedule_patience: 10
  min_lr: 1e-5